"""Phase 1 Stage 0 regression anchors for the legacy Cartesian LGN."""

import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import numpy as np
import pytest

RF_TYPES = ("X_ON", "X_OFF")
SIGNATURE_PREFIX = "LEGACY_LGN_SIGNATURE="
PROBE_ARGUMENT = "--legacy-lgn-probe"

# This fixture intentionally uses the legacy input component with two cells per
# polarity. It is small enough for the mandatory one-/two-rank matrix while
# still exercising seeded positions, ON/OFF kernels, stimulus convolution,
# nonlinear gain, and StepCurrentSource injection.
LEGACY_MODEL_PARAMETERS = {
    "input_space_type": "mozaik.space.VisualSpace",
    "input_space": {"update_interval": 7.0, "background_luminance": 45.0},
    "sheets": {
        "retina_lgn": {
            "params": {
                "density": 10,
                "size": (0.5, 0.5),
                "linear_scaler": 6.0,
                "mpi_reproducible_noise": False,
                "recorders": {},
                "recording_interval": 1.0,
                "receptive_field": {
                    "func": "cai97.stRF_2d",
                    "func_params": {
                        "Ac": 1.0,
                        "As": 0.3,
                        "K1": 1.05,
                        "K2": 0.7,
                        "c1": 0.14,
                        "c2": 0.12,
                        "n1": 7.0,
                        "n2": 8.0,
                        "t1": -6.0,
                        "t2": -6.0,
                        "td": 6.0,
                        "sigma_c": 0.4,
                        "sigma_s": 1.0,
                        "subtract_mean": False,
                    },
                    "width": 6.0,
                    "height": 6.0,
                    "spatial_resolution": 0.1,
                    "temporal_resolution": 7.0,
                    "duration": 200.0,
                },
                "original_2024_lgn_mode": False,
                "gain_control": {
                    "gain": 1.0,
                    "non_linear_gain": {
                        "contrast_gain": 0.11,
                        "contrast_scaler": 0.00013,
                        "luminance_gain": 0.009,
                        "luminance_scaler": 0.4,
                    },
                },
                "cell": {
                    "model": "IF_cond_exp",
                    "native_nest": False,
                    "params": {
                        "v_thresh": -57.0,
                        "v_rest": -70.0,
                        "v_reset": -70.0,
                        "tau_refrac": 2.0,
                        "tau_m": 10.0,
                        "cm": 0.29,
                        "e_rev_E": 0.0,
                        "e_rev_I": -75.0,
                        "tau_syn_E": 1.5,
                        "tau_syn_I": 10.0,
                    },
                    "receptors": None,
                    "initial_values": {"v": -70.0},
                },
                "noise": {"mean": 0.0, "stdev": 0.0},
            }
        }
    },
    "results_dir": "",
    "name": "LegacyLGNCharacterization",
    "reset": False,
    "null_stimulus_period": 150.0,
    "store_stimuli": False,
    "min_delay": 0.1,
    "max_delay": 100.0,
    "time_step": 0.1,
    "pynn_seed": 936395,
    "mpi_seed": 1023,
    "explosion_monitoring": None,
    "steps_get_data": 0,
}

STIMULUS_DURATION_MS = 28.0
LEGACY_STIMULUS_PARAMETERS = {
    "frame_duration": 7.0,
    "duration": STIMULUS_DURATION_MS,
    "trial": 0,
    "background_luminance": 45.0,
    "density": 10.0,
    "location_x": 0.0,
    "location_y": 0.0,
    "size_x": 7.0,
    "size_y": 7.0,
    "orientation": 0.0,
    "spatial_frequency": 0.5,
    "temporal_frequency": 1000.0 / STIMULUS_DURATION_MS,
    "contrast": 50.0,
}

# Generated by this module's probe with NEST 3.4 and PyNN 0.12.4.
EXPECTED_LEGACY_LGN_SIGNATURE = {
    "counts": {"X_OFF": 2, "X_ON": 2},
    "injected_current_amplitudes_na": {
        "X_OFF": [
            [
                0.00011504283917343079,
                0.008891367854129166,
                0.049517154716325354,
                0.07753297453968991,
            ],
            [
                -0.00011160806620317145,
                -0.009191454834730727,
                -0.07036655649225218,
                -0.19158275475708714,
            ],
        ],
        "X_ON": [
            [
                -1.717386485129783e-06,
                0.00019106017566118965,
                0.01523413597964365,
                0.096143405787109,
            ],
            [
                0.00011160806620317145,
                0.009191454834730727,
                0.07036655649225218,
                0.19158275475708714,
            ],
        ],
    },
    "injected_current_times_ms": {
        "X_OFF": [
            [0.1, 6.9, 13.9, 20.900000000000002],
            [0.1, 6.9, 13.9, 20.900000000000002],
        ],
        "X_ON": [
            [0.1, 6.9, 13.9, 20.900000000000002],
            [0.1, 6.9, 13.9, 20.900000000000002],
        ],
    },
    "kernel_response_shapes": {"X_OFF": [2, 33], "X_ON": [2, 33]},
    "kernel_shapes": {"X_OFF": [60, 60, 29], "X_ON": [60, 60, 29]},
    "positions_deg": {
        "X_OFF": [
            [-0.16341226425105004, 0.06485247604341415],
            [-0.16825410111728178, 0.21494977406820848],
            [0.0, 0.0],
        ],
        "X_ON": [
            [-0.0491076893956946, -0.0004328797422454844],
            [0.009586449976160594, 0.23772671414385232],
            [0.0, 0.0],
        ],
    },
    "stimulus_resolution_deg": 0.1,
}

REGRESSION_RTOL = 1e-12
REGRESSION_ATOL = 1e-17
CURRENT_ATOL = 1e-14
DENSE_FACTORIZED_ATOL = {
    "kernel": REGRESSION_ATOL,
    "contrast_response": REGRESSION_ATOL,
    "luminance_response": REGRESSION_ATOL,
    "injected_current": CURRENT_ATOL,
}


def _sha256_float64(array):
    import numpy as np

    canonical = np.array(array, dtype=np.dtype("<f8"), order="C", copy=True)
    # Match numpy.array_equal semantics: IEEE -0.0 and +0.0 are equal even
    # though their byte representations differ.
    canonical[canonical == 0.0] = 0.0
    return hashlib.sha256(canonical.tobytes()).hexdigest()


def _all_ranks_equal(comm, value, description):
    values = comm.allgather(value)
    if any(other != values[0] for other in values[1:]):
        raise AssertionError(f"{description} differs across MPI ranks: {values}")


def _gather_local_arrays(comm, local_arrays):
    import numpy as np

    gathered = comm.gather(local_arrays, root=0)
    if comm.rank != 0:
        return None

    global_arrays = {}
    for rank_arrays in gathered:
        for global_index, array in rank_arrays:
            if global_index in global_arrays:
                raise AssertionError(
                    f"Global LGN index {global_index} was owned by multiple ranks"
                )
            global_arrays[global_index] = array

    expected_indices = list(range(len(global_arrays)))
    if sorted(global_arrays) != expected_indices:
        raise AssertionError(
            "Global LGN ownership did not reconstruct a contiguous index range: "
            f"{sorted(global_arrays)}"
        )
    return np.stack([global_arrays[index] for index in expected_indices])


def _collect_legacy_lgn_signature(use_factorization):
    import copy

    import mozaik
    from mozaik.models import Model
    from mozaik.models.vision import cai97
    from mozaik.models.vision.spatiotemporalfilter import (
        SpatioTemporalFilterRetinaLGN,
    )
    from mozaik.space import VisualRegion
    from mozaik.stimuli.vision.topographica_based import (
        FullfieldDriftingSinusoidalGrating,
    )
    from parameters import ParameterSet
    from pyNN import nest

    parameters = ParameterSet(copy.deepcopy(LEGACY_MODEL_PARAMETERS))
    mozaik.setup_mpi(parameters.mpi_seed, parameters.pynn_seed)
    comm = mozaik.mpi_comm
    model = Model(nest, 1, parameters)
    model.visual_field = VisualRegion(
        location_x=0.0,
        location_y=0.0,
        size_x=7.0,
        size_y=7.0,
    )

    try:
        factorizer = cai97.stRF_2d.factorize
        if not use_factorization:
            cai97.stRF_2d.factorize = None
        try:
            retina = SpatioTemporalFilterRetinaLGN(
                model, parameters.sheets.retina_lgn.params
            )
        finally:
            cai97.stRF_2d.factorize = factorizer
        stimulus = FullfieldDriftingSinusoidalGrating(**LEGACY_STIMULUS_PARAMETERS)
        model.input_space.add_object(str(stimulus), stimulus)
        kernel_responses, _ = retina.calculate_kernel_responses(
            model.input_space, STIMULUS_DURATION_MS
        )
        currents = retina._calculate_input_currents(kernel_responses)
        retina.inject_currents(currents, STIMULUS_DURATION_MS)

        signature = {
            "counts": {},
            "positions_deg": {},
            "kernel_shapes": {},
            "kernel_response_shapes": {},
            "injected_current_times_ms": {},
            "injected_current_amplitudes_na": {},
            "stimulus_resolution_deg": float(retina.rf["X_ON"].spatial_resolution),
            "_kernels": {},
            "_kernel_response_contrast": {},
            "_kernel_response_luminance": {},
        }

        for rf_type in RF_TYPES:
            sheet = retina.sheets[rf_type]
            positions = sheet.pop.positions
            position_list = positions.tolist()
            kernel = retina.rf[rf_type].as_dense()

            _all_ranks_equal(
                comm,
                position_list,
                f"{rf_type} global positions",
            )
            _all_ranks_equal(
                comm,
                _sha256_float64(kernel),
                f"{rf_type} receptive-field kernel",
            )

            local_response_contrast = []
            local_response_luminance = []
            local_injected_current = []
            local_index = 0
            for global_index, is_local in enumerate(sheet.pop._mask_local):
                if not is_local:
                    continue
                response = kernel_responses[rf_type][local_index]
                current_source = retina.scs[rf_type][local_index]
                local_response_contrast.append((global_index, response.contrast))
                local_response_luminance.append((global_index, response.luminance))
                local_injected_current.append(
                    (
                        global_index,
                        [
                            current_source.times.evaluate(),
                            current_source.amplitudes.evaluate(),
                        ],
                    )
                )
                local_index += 1

            response_contrast = _gather_local_arrays(comm, local_response_contrast)
            response_luminance = _gather_local_arrays(comm, local_response_luminance)
            injected_current = _gather_local_arrays(comm, local_injected_current)

            if comm.rank == 0:
                signature["counts"][rf_type] = int(sheet.pop.size)
                signature["positions_deg"][rf_type] = position_list
                signature["kernel_shapes"][rf_type] = list(kernel.shape)
                signature["kernel_response_shapes"][rf_type] = list(
                    response_contrast.shape
                )
                signature["injected_current_times_ms"][rf_type] = injected_current[
                    :, 0, :
                ].tolist()
                signature["injected_current_amplitudes_na"][rf_type] = injected_current[
                    :, 1, :
                ].tolist()
                signature["_kernels"][rf_type] = kernel
                signature["_kernel_response_contrast"][rf_type] = response_contrast
                signature["_kernel_response_luminance"][rf_type] = response_luminance

        return signature if comm.rank == 0 else None
    finally:
        model.sim.end()


def _collect_dense_factorized_comparison():
    dense = _collect_legacy_lgn_signature(use_factorization=False)
    factorized = _collect_legacy_lgn_signature(use_factorization=True)
    if factorized is None:
        return None

    comparisons = {
        "kernel": "_kernels",
        "contrast_response": "_kernel_response_contrast",
        "luminance_response": "_kernel_response_luminance",
        "injected_current": "injected_current_amplitudes_na",
    }
    factorized["dense_factorized_max_abs_error"] = {
        name: max(
            float(
                np.max(
                    np.abs(
                        np.asarray(factorized[field][rf_type])
                        - np.asarray(dense[field][rf_type])
                    )
                )
            )
            for rf_type in RF_TYPES
        )
        for name, field in comparisons.items()
    }
    factorized["dense_factorized_matches"] = {
        name: all(
            np.allclose(
                factorized[field][rf_type],
                dense[field][rf_type],
                rtol=REGRESSION_RTOL,
                atol=DENSE_FACTORIZED_ATOL[name],
            )
            for rf_type in RF_TYPES
        )
        for name, field in comparisons.items()
    }
    for field in (
        "_kernels",
        "_kernel_response_contrast",
        "_kernel_response_luminance",
    ):
        factorized.pop(field)
    return factorized


def _run_probe(process_count):
    command = [sys.executable, str(Path(__file__).resolve()), PROBE_ARGUMENT]
    if process_count > 1:
        command = ["mpirun", "--oversubscribe", "-np", str(process_count), *command]

    environment = os.environ.copy()
    repository_root = Path(__file__).resolve().parents[3]
    environment["PYTHONPATH"] = os.pathsep.join(
        filter(
            None,
            (str(repository_root), environment.get("PYTHONPATH")),
        )
    )
    result = subprocess.run(
        command,
        cwd=repository_root,
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
        timeout=30,
    )
    if result.returncode != 0:
        pytest.fail(
            "\n".join(
                [
                    f"Legacy LGN probe failed with {process_count} rank(s)",
                    f"Return code: {result.returncode}",
                    "===== stdout =====",
                    result.stdout or "<empty>",
                    "===== stderr =====",
                    result.stderr or "<empty>",
                ]
            )
        )

    signature_lines = [
        line for line in result.stdout.splitlines() if line.startswith(SIGNATURE_PREFIX)
    ]
    assert len(signature_lines) == 1, result.stdout
    return json.loads(signature_lines[0][len(SIGNATURE_PREFIX) :])


def _assert_legacy_lgn_signature(signature):
    errors = signature.pop("dense_factorized_max_abs_error")
    matches = signature.pop("dense_factorized_matches")
    for name, tolerance in DENSE_FACTORIZED_ATOL.items():
        assert matches[name], (
            f"dense and factorized {name} differ: max absolute error "
            f"{errors[name]}, rtol={REGRESSION_RTOL}, atol={tolerance}"
        )

    for name in (
        "counts",
        "kernel_shapes",
        "kernel_response_shapes",
    ):
        assert signature[name] == EXPECTED_LEGACY_LGN_SIGNATURE[name]
    np.testing.assert_allclose(
        signature["stimulus_resolution_deg"],
        EXPECTED_LEGACY_LGN_SIGNATURE["stimulus_resolution_deg"],
        rtol=REGRESSION_RTOL,
        atol=REGRESSION_ATOL,
    )

    for rf_type in RF_TYPES:
        for name in ("positions_deg", "injected_current_times_ms"):
            np.testing.assert_allclose(
                signature[name][rf_type],
                EXPECTED_LEGACY_LGN_SIGNATURE[name][rf_type],
                rtol=REGRESSION_RTOL,
                atol=REGRESSION_ATOL,
            )
        np.testing.assert_allclose(
            signature["injected_current_amplitudes_na"][rf_type],
            EXPECTED_LEGACY_LGN_SIGNATURE["injected_current_amplitudes_na"][rf_type],
            rtol=REGRESSION_RTOL,
            atol=CURRENT_ATOL,
        )


def test_legacy_lgn_single_process_regression():
    _assert_legacy_lgn_signature(_run_probe(process_count=1))


@pytest.mark.mpi
def test_legacy_lgn_two_rank_regression():
    _assert_legacy_lgn_signature(_run_probe(process_count=2))


@pytest.mark.mpi
def test_legacy_lgn_uneven_rank_regression():
    _assert_legacy_lgn_signature(_run_probe(process_count=3))


if __name__ == "__main__" and PROBE_ARGUMENT in sys.argv:
    probe_signature = _collect_dense_factorized_comparison()
    if probe_signature is not None:
        print(SIGNATURE_PREFIX + json.dumps(probe_signature, sort_keys=True))
