"""Phase 1 Stage 0 regression anchors for the legacy Cartesian LGN."""

import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest

RF_TYPES = ("X_ON", "X_OFF")
SIGNATURE_PREFIX = "LEGACY_LGN_SIGNATURE="
PROBE_ARGUMENT = "--legacy-lgn-probe"

# This fixture intentionally uses the legacy input component with two cells per
# polarity. It is small enough for the mandatory one-/two-rank matrix while
# still exercising seeded positions, ON/OFF kernels, stimulus convolution,
# nonlinear gain, and StepCurrentSource injection.
LEGACY_MODEL_PARAMETERS = {
    "input_space_type": "mozaik.space.VisualSpace",
    "input_space": {"update_interval": 7.0, "background_luminance": 45.0},
    "sheets": {
        "retina_lgn": {
            "params": {
                "density": 10,
                "size": (0.5, 0.5),
                "linear_scaler": 6.0,
                "mpi_reproducible_noise": False,
                "recorders": {},
                "recording_interval": 1.0,
                "receptive_field": {
                    "func": "cai97.stRF_2d",
                    "func_params": {
                        "Ac": 1.0,
                        "As": 0.3,
                        "K1": 1.05,
                        "K2": 0.7,
                        "c1": 0.14,
                        "c2": 0.12,
                        "n1": 7.0,
                        "n2": 8.0,
                        "t1": -6.0,
                        "t2": -6.0,
                        "td": 6.0,
                        "sigma_c": 0.4,
                        "sigma_s": 1.0,
                        "subtract_mean": False,
                    },
                    "width": 6.0,
                    "height": 6.0,
                    "spatial_resolution": 0.1,
                    "temporal_resolution": 7.0,
                    "duration": 200.0,
                },
                "original_2024_lgn_mode": False,
                "gain_control": {
                    "gain": 1.0,
                    "non_linear_gain": {
                        "contrast_gain": 0.11,
                        "contrast_scaler": 0.00013,
                        "luminance_gain": 0.009,
                        "luminance_scaler": 0.4,
                    },
                },
                "cell": {
                    "model": "IF_cond_exp",
                    "native_nest": False,
                    "params": {
                        "v_thresh": -57.0,
                        "v_rest": -70.0,
                        "v_reset": -70.0,
                        "tau_refrac": 2.0,
                        "tau_m": 10.0,
                        "cm": 0.29,
                        "e_rev_E": 0.0,
                        "e_rev_I": -75.0,
                        "tau_syn_E": 1.5,
                        "tau_syn_I": 10.0,
                    },
                    "receptors": None,
                    "initial_values": {"v": -70.0},
                },
                "noise": {"mean": 0.0, "stdev": 0.0},
            }
        }
    },
    "results_dir": "",
    "name": "LegacyLGNCharacterization",
    "reset": False,
    "null_stimulus_period": 150.0,
    "store_stimuli": False,
    "min_delay": 0.1,
    "max_delay": 100.0,
    "time_step": 0.1,
    "pynn_seed": 936395,
    "mpi_seed": 1023,
    "explosion_monitoring": None,
    "steps_get_data": 0,
}

STIMULUS_DURATION_MS = 28.0
LEGACY_STIMULUS_PARAMETERS = {
    "frame_duration": 7.0,
    "duration": STIMULUS_DURATION_MS,
    "trial": 0,
    "background_luminance": 45.0,
    "density": 10.0,
    "location_x": 0.0,
    "location_y": 0.0,
    "size_x": 7.0,
    "size_y": 7.0,
    "orientation": 0.0,
    "spatial_frequency": 0.5,
    "temporal_frequency": 1000.0 / STIMULUS_DURATION_MS,
    "contrast": 50.0,
}

# Generated by this module's probe with NEST 3.4 and PyNN 0.12.4. Arrays are
# represented directly where compact; full kernels and response buffers use a
# canonical little-endian float64 SHA-256 digest.
EXPECTED_LEGACY_LGN_SIGNATURE = {
    "counts": {"X_OFF": 2, "X_ON": 2},
    "injected_current_amplitudes_na": {
        "X_OFF": [
            [
                0.00011504283917343079,
                0.008891367854129166,
                0.049517154716325354,
                0.07753297453968991,
            ],
            [
                -0.00011160806620317145,
                -0.009191454834730727,
                -0.07036655649225218,
                -0.19158275475708714,
            ],
        ],
        "X_ON": [
            [
                -1.717386485129783e-06,
                0.00019106017566118965,
                0.01523413597964365,
                0.096143405787109,
            ],
            [
                0.00011160806620317145,
                0.009191454834730727,
                0.07036655649225218,
                0.19158275475708714,
            ],
        ],
    },
    "injected_current_times_ms": {
        "X_OFF": [
            [0.1, 6.9, 13.9, 20.900000000000002],
            [0.1, 6.9, 13.9, 20.900000000000002],
        ],
        "X_ON": [
            [0.1, 6.9, 13.9, 20.900000000000002],
            [0.1, 6.9, 13.9, 20.900000000000002],
        ],
    },
    "kernel_response_luminance_sha256": {
        "X_OFF": "7964da67ec439ccaa0dffbf7d39cfb35529208813e7950536bf395b87d565066",
        "X_ON": "8b8bb5391c2afdbce4220598ea8f3452e713598af025361196b94240decae5a5",
    },
    "kernel_response_shapes": {"X_OFF": [2, 33], "X_ON": [2, 33]},
    "kernel_sha256": {
        "X_OFF": "4f25206638751b767045908d904fe9560d834585d392b4d955cdb678d5625b31",
        "X_ON": "bcad09ceb91a121223118a0fbbf3517462c05640f4b03ff6bc1120d0c5737567",
    },
    "kernel_shapes": {"X_OFF": [60, 60, 29], "X_ON": [60, 60, 29]},
    "positions_deg": {
        "X_OFF": [
            [-0.16341226425105004, 0.06485247604341415],
            [-0.16825410111728178, 0.21494977406820848],
            [0.0, 0.0],
        ],
        "X_ON": [
            [-0.0491076893956946, -0.0004328797422454844],
            [0.009586449976160594, 0.23772671414385232],
            [0.0, 0.0],
        ],
    },
    "stimulus_resolution_deg": 0.1,
}

# The full legacy contrast-response buffer includes the post-presentation
# convolution tail. Its byte-exact value currently depends on whether the two
# cells are evaluated on one rank or split across two ranks, while the
# stimulus-window currents above are identical. Stage 0 records both existing
# outcomes instead of redefining that legacy behavior.
EXPECTED_CONTRAST_RESPONSE_SHA256_BY_PROCESS_COUNT = {
    1: {
        "X_OFF": "c36d5834f2172428b01dff46f0f717a89cbcbc98a902064a74bbe274c5667fdc",
        "X_ON": "116b5c146bae6fa6a940f2ce201a5bc7da1eecfc46842b863883a61b8420f3f0",
    },
    2: {
        "X_OFF": "f5bf8be76eb33058a0cf2b0924da8079c59fe99b8986063c690b9857039113ec",
        "X_ON": "34fef7cb9174dd565ae0fb01903a09a83470b02548beda3b8c7e00db8f96ce2d",
    },
}


def _sha256_float64(array):
    import numpy as np

    canonical = np.array(array, dtype=np.dtype("<f8"), order="C", copy=True)
    # Match numpy.array_equal semantics: IEEE -0.0 and +0.0 are equal even
    # though their byte representations differ.
    canonical[canonical == 0.0] = 0.0
    return hashlib.sha256(canonical.tobytes()).hexdigest()


def _all_ranks_equal(comm, value, description):
    values = comm.allgather(value)
    if any(other != values[0] for other in values[1:]):
        raise AssertionError(f"{description} differs across MPI ranks: {values}")


def _gather_local_arrays(comm, local_arrays):
    import numpy as np

    gathered = comm.gather(local_arrays, root=0)
    if comm.rank != 0:
        return None

    global_arrays = {}
    for rank_arrays in gathered:
        for global_index, array in rank_arrays:
            if global_index in global_arrays:
                raise AssertionError(
                    f"Global LGN index {global_index} was owned by multiple ranks"
                )
            global_arrays[global_index] = array

    expected_indices = list(range(len(global_arrays)))
    if sorted(global_arrays) != expected_indices:
        raise AssertionError(
            "Global LGN ownership did not reconstruct a contiguous index range: "
            f"{sorted(global_arrays)}"
        )
    return np.stack([global_arrays[index] for index in expected_indices])


def _collect_legacy_lgn_signature():
    import copy

    import mozaik
    from mozaik.models import Model
    from mozaik.models.vision.spatiotemporalfilter import (
        SpatioTemporalFilterRetinaLGN,
    )
    from mozaik.space import VisualRegion
    from mozaik.stimuli.vision.topographica_based import (
        FullfieldDriftingSinusoidalGrating,
    )
    from parameters import ParameterSet
    from pyNN import nest

    parameters = ParameterSet(copy.deepcopy(LEGACY_MODEL_PARAMETERS))
    mozaik.setup_mpi(parameters.mpi_seed, parameters.pynn_seed)
    comm = mozaik.mpi_comm
    model = Model(nest, 1, parameters)
    model.visual_field = VisualRegion(
        location_x=0.0,
        location_y=0.0,
        size_x=7.0,
        size_y=7.0,
    )

    try:
        retina = SpatioTemporalFilterRetinaLGN(
            model, parameters.sheets.retina_lgn.params
        )
        stimulus = FullfieldDriftingSinusoidalGrating(**LEGACY_STIMULUS_PARAMETERS)
        model.input_space.add_object(str(stimulus), stimulus)
        kernel_responses, _ = retina.calculate_kernel_responses(
            model.input_space, STIMULUS_DURATION_MS
        )
        currents = retina._calculate_input_currents(kernel_responses)
        retina.inject_currents(currents, STIMULUS_DURATION_MS)

        signature = {
            "counts": {},
            "positions_deg": {},
            "kernel_shapes": {},
            "kernel_sha256": {},
            "kernel_response_shapes": {},
            "kernel_response_contrast_sha256": {},
            "kernel_response_luminance_sha256": {},
            "injected_current_times_ms": {},
            "injected_current_amplitudes_na": {},
            "stimulus_resolution_deg": float(retina.rf["X_ON"].spatial_resolution),
        }

        for rf_type in RF_TYPES:
            sheet = retina.sheets[rf_type]
            positions = sheet.pop.positions
            position_list = positions.tolist()
            kernel = retina.rf[rf_type].kernel

            _all_ranks_equal(
                comm,
                position_list,
                f"{rf_type} global positions",
            )
            _all_ranks_equal(
                comm,
                _sha256_float64(kernel),
                f"{rf_type} receptive-field kernel",
            )

            local_response_contrast = []
            local_response_luminance = []
            local_injected_current = []
            local_index = 0
            for global_index, is_local in enumerate(sheet.pop._mask_local):
                if not is_local:
                    continue
                response = kernel_responses[rf_type][local_index]
                current_source = retina.scs[rf_type][local_index]
                local_response_contrast.append((global_index, response.contrast))
                local_response_luminance.append((global_index, response.luminance))
                local_injected_current.append(
                    (
                        global_index,
                        [
                            current_source.times.evaluate(),
                            current_source.amplitudes.evaluate(),
                        ],
                    )
                )
                local_index += 1

            response_contrast = _gather_local_arrays(comm, local_response_contrast)
            response_luminance = _gather_local_arrays(comm, local_response_luminance)
            injected_current = _gather_local_arrays(comm, local_injected_current)

            if comm.rank == 0:
                signature["counts"][rf_type] = int(sheet.pop.size)
                signature["positions_deg"][rf_type] = position_list
                signature["kernel_shapes"][rf_type] = list(kernel.shape)
                signature["kernel_sha256"][rf_type] = _sha256_float64(kernel)
                signature["kernel_response_shapes"][rf_type] = list(
                    response_contrast.shape
                )
                signature["kernel_response_contrast_sha256"][rf_type] = _sha256_float64(
                    response_contrast
                )
                signature["kernel_response_luminance_sha256"][rf_type] = (
                    _sha256_float64(response_luminance)
                )
                signature["injected_current_times_ms"][rf_type] = injected_current[
                    :, 0, :
                ].tolist()
                signature["injected_current_amplitudes_na"][rf_type] = injected_current[
                    :, 1, :
                ].tolist()

        return signature if comm.rank == 0 else None
    finally:
        model.sim.end()


def _run_probe(process_count):
    command = [sys.executable, str(Path(__file__).resolve()), PROBE_ARGUMENT]
    if process_count == 2:
        command = ["mpirun", "--oversubscribe", "-np", "2", *command]

    result = subprocess.run(
        command,
        cwd=Path(__file__).resolve().parents[3],
        env=os.environ.copy(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(
            "\n".join(
                [
                    f"Legacy LGN probe failed with {process_count} rank(s)",
                    f"Return code: {result.returncode}",
                    "===== stdout =====",
                    result.stdout or "<empty>",
                    "===== stderr =====",
                    result.stderr or "<empty>",
                ]
            )
        )

    signature_lines = [
        line for line in result.stdout.splitlines() if line.startswith(SIGNATURE_PREFIX)
    ]
    assert len(signature_lines) == 1, result.stdout
    return json.loads(signature_lines[0][len(SIGNATURE_PREFIX) :])


def _assert_legacy_lgn_signature(signature, process_count):
    contrast_response_signature = signature.pop("kernel_response_contrast_sha256")
    assert (
        contrast_response_signature
        == EXPECTED_CONTRAST_RESPONSE_SHA256_BY_PROCESS_COUNT[process_count]
    )
    assert signature == EXPECTED_LEGACY_LGN_SIGNATURE


def test_legacy_lgn_single_process_regression():
    _assert_legacy_lgn_signature(_run_probe(process_count=1), process_count=1)


@pytest.mark.mpi
def test_legacy_lgn_two_rank_regression():
    _assert_legacy_lgn_signature(_run_probe(process_count=2), process_count=2)


if __name__ == "__main__" and PROBE_ARGUMENT in sys.argv:
    probe_signature = _collect_legacy_lgn_signature()
    if probe_signature is not None:
        print(SIGNATURE_PREFIX + json.dumps(probe_signature, sort_keys=True))
